"""añadir tablas comparados, aprobados e historial

Revision ID: 2d2d927f3745
Revises: 4fabc96e7975
Create Date: 2025-07-04 02:44:40.925922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d2d927f3745'
down_revision: Union[str, Sequence[str], None] = '4fabc96e7975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos_comparados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_scrapeado', sa.String(), nullable=False),
    sa.Column('url_amazon', sa.String(), nullable=False),
    sa.Column('asin', sa.String(), nullable=False),
    sa.Column('precio_amazon', sa.Float(), nullable=False),
    sa.Column('rentabilidad_fba', sa.Float(), nullable=False),
    sa.Column('rentabilidad_drops', sa.Float(), nullable=False),
    sa.Column('estimacion_ventas', sa.Integer(), nullable=False),
    sa.Column('fecha_comparacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_scrapeado'], ['productos_scrapeados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos_aprobados',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_comparado', sa.String(), nullable=False),
    sa.Column('metodo_venta', sa.String(), nullable=False),
    sa.Column('precio_tienda', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_comparado'], ['productos_comparados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historial_precios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('id_aprobado', sa.String(), nullable=False),
    sa.Column('precio_amazon', sa.Float(), nullable=False),
    sa.Column('margen_actual', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aprobado'], ['productos_aprobados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('plan', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan')
    op.drop_table('historial_precios')
    op.drop_table('productos_aprobados')
    op.drop_table('productos_comparados')
    # ### end Alembic commands ###
